export const SHRINK_LEFT_SIDEBAR = 'SHRINK_LEFT_SIDEBAR';
export const SET_ECOMMERCE_CHECKOUT_STEP = 'SET_ECOMMERCE_CHECKOUT_STEP';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS';